# hub-service.yml
server:
  port: 8082

custom:
  db:
    schema: hub_service

kakao:
  mobility:
  rest-api-key: ${KAKAO_MOBILITY_REST_API_KEY}
  directions-base-url: https://apis-navi.kakaomobility.com