# hub-service.yml
server:
  port: 8082

custom:
  db:
    schema: hub_service

naver:
  map:
    client-id: ${NAVER_MAP_CLIENT_ID}
    client-secret: ${NAVER_MAP_CLIENT_SECRET}
    direction-base-url: https://naveropenapi.apigw.ntruss.com/map-direction/v1
    geocode-base-url: https://naveropenapi.apigw.ntruss.com/map-geocode/v2