# common/application.yml

custom:
  db:
    host: ${POSTGRES_HOST:localhost}
    port: ${POSTGRES_PORT:5432}
    name: ${DB_NAME:da_it_da_db}
    # schema: 각 서비스에서 반드시 정의해야 함 (예: user_service)

spring:
  datasource:
    # 각 서비스의 custom.db.schema 값을 받아 URL 조립
    url: jdbc:postgresql://${custom.db.host}:${custom.db.port}/${custom.db.name}?currentSchema=${custom.db.schema}
    username: ${DB_USERNAME:postgres_daitda}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 5000
            response-timeout: 5s

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        default_schema: ${custom.db.schema}
        format_sql: true

eureka:
  client:
    register-with-eureka: true # 명시적으로 작성하여 가독성 확보
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        slowCallDurationThreshold: 3000ms 
        slowCallRateThreshold: 60
        failureRateThreshold: 50
        waitDurationInOpenState: 20s
        permittedNumberOfCallsInHalfOpenState: 3
        # 서킷 브레이커가 전이될 때 로그를 남기도록 설정 (디버깅용)
        eventConsumerBufferSize: 10
        
  timelimiter:
    configs:
      default:
        # [중요] CircuitBreaker의 slowCall보다 이 타임아웃이 우선순위가 높습니다.
        # 서비스 응답이 5초를 넘기면 강제로 종료하고 Fallback을 실행합니다.
        timeoutDuration: 5s

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,metrics