# common/application.yml

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # Eureka 서버 주소도 환경 변수로 관리 (기본값은 localhost)
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

spring:
  # 1. PostgreSQL 설정
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # 2. Redis 설정
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  # 3. JPA/Hibernate 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# 4. Zipkin (Tracing) 설정
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}/api/v2/spans

# 5. Keycloak 설정
keycloak:
  auth-server-url: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:9090}
  admin-user: ${KC_ADMIN_USER:dnjswns}
  admin-password: ${KC_ADMIN_PASSWORD:dnjswns123!}