# user-service/user-service.yml
server:
  port: 8081

# 서비스 고유의 비즈니스 설정 예시
user-service:
  message: "이 메시지는 Config Server의 user-service.yml에서 불러온 메시지입니다."
  feature-x-enabled: true

# 로그 레벨 개별 설정
logging:
  level:
    com.example.userservice: DEBUG