# user-service/user-service.yml
custom:
  db:
    schema: user_service

server:
  port: 8081

keycloak:
  server-url: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:9090}
  realm: ${KEYCLOAK_REALM:da-it-da-realm}
  admin:
    username: ${KEYCLOAK_ADMIN_USERNAME}
    password: ${KEYCLOAK_ADMIN_PASSWORD}
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID}
  user:
    client-id: ${KEYCLOAK_USER_CLIENT_ID}

spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}